# general settings
name: train_HAT-L_SRx8_finetune_from_ImageNet_pretrain
model_type: HATModel
scale: 8
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: thermal
    type: PairedImageDataset
    dataroot_gt: datasets/train/GT
    dataroot_lq: datasets/train/LR_x8
    io_backend:
      type: disk

    gt_size: 384
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4 # 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: thermal
    type: PairedImageDataset
    dataroot_gt: ./datasets/val/GT
    dataroot_lq: ./datasets/val/LR_x8
    io_backend:
      type: disk


# network structures
network_g:
  type: HAT
  upscale: 8
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ./pretrained_models/HAT-L_SRx4_ImageNet-pretrain.pth
  param_key_g: 'params_ema'
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [25000, 25000, 25000, 25000]
    restart_weights: [1, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 20000
  warmup_iter: 1000  # no warm up

  # losses
  pixel_opt:
    type: MultiLoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e3
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
